---
- name: copy script
  hosts: all

  tasks:

  - name: Add Cron job
    cron:
        name: Adding test script to cron
        state: present
        minute: "10"
        hour: "15"
        day: "*"
        month: "*"
        weekday: "*"
        user: smitra
        job: /home/smitra/scripts/test.sh

